# Ввод данных от пользователя
print('Введите данные')
s = input()
print(s)
print('Введите ЦЕЛОЕ число')
t = int(input())
print(s , t)
s = input('Введите свое имя: ')
print('Привет', s)
s = float(input('Введите число: '))
print(s*2)
print('Введите два числа')
a = float(input('Введите первое число: '))
b = float(input('Введите второе число: '))
print('Произведение чисел равно: ', a * b)